export const medicalHistoryCategories = {
  "General Medical History": [
    "Diabetes",
    "Hypertension (General)",
    "Tuberculosis",
    "Asthma",
    "Allergy history (General)",
    "Surgical history",
    "Currently Taking Medications",
    "Family medical history",
    "Personal habits",
  ],
  "Orthopedic History": [
    "Joint pain",
    "Swelling (Ortho)",
    "Morning stiffness (Ortho)",
    "Trauma/injury history",
    "Fracture history",
    "Difficulty walking",
    "Limb deformity",
    "Muscle wasting",
    "Back pain",
    "Neck pain",
    "Restricted movements",
    "Instability of joints",
    "Clicking sounds",
    "Previous orthopedic surgery",
    "Use of walking aids",
  ],
  "Neurology History": [
    "Headache",
    "Dizziness",
    "Seizures",
    "Weakness",
    "Paralysis",
    "Numbness",
    "Tingling sensation",
    "Loss of consciousness",
    "Memory loss",
    "Tremors",
    "Difficulty speaking",
    "Difficulty swallowing (Neuro)",
    "Gait imbalance",
    "Facial deviation",
    "Sleep disturbances (Neuro)",
  ],
  "Ophthalmology History": [
    "Blurred vision",
    "Eye redness",
    "Eye pain",
    "Watering",
    "Itching (Eye)",
    "Foreign body sensation",
    "Photophobia",
    "Double vision",
    "Vision loss",
    "Night blindness",
    "Previous eye surgery",
    "Spectacle usage",
    "Contact lens usage",
    "Eye trauma history",
  ],
  "ENT History": [
    "Ear pain",
    "Ear discharge",
    "Hearing loss",
    "Tinnitus",
    "Vertigo",
    "Nasal blockage",
    "Sneezing",
    "Epistaxis",
    "Sinus pain",
    "Sore throat",
    "Difficulty swallowing (ENT)",
    "Voice change",
    "Snoring",
  ],
  "Cardiology History": [
    "Chest pain",
    "Palpitations",
    "Breathlessness (Cardiac)",
    "Orthopnea",
    "Pedal edema",
    "Syncope",
    "Hypertension (Cardiac)",
    "Previous MI history",
    "Rheumatic heart disease",
    "Fatigue (Cardiac)",
    "Exercise intolerance",
  ],
  "Respiratory History": [
    "Dry cough",
    "Productive cough",
    "Breathlessness (Respiratory)",
    "Wheezing",
    "Fever",
    "Chest tightness",
    "Hemoptysis",
    "Smoking history",
    "Asthma history",
    "Tuberculosis history",
    "Occupational exposure",
  ],
  "Gastroenterology History": [
    "Abdominal pain",
    "Vomiting",
    "Nausea",
    "Diarrhea",
    "Constipation",
    "Bloating",
    "Loss of appetite (GI)",
    "Weight loss (GI)",
    "Jaundice",
    "Hematemesis",
    "Melena",
    "Acid reflux",
  ],
  "Nephrology / Urology History": [
    "Burning micturition",
    "Increased frequency",
    "Hematuria",
    "Reduced urine output",
    "Flank pain",
    "Urinary incontinence",
    "Renal stone history",
    "Swelling of legs",
    "Dialysis history",
  ],
  "Gynecology History": [
    "Irregular menstruation",
    "Dysmenorrhea",
    "Menorrhagia",
    "Vaginal discharge",
    "Pelvic pain",
    "Infertility",
    "Menopause symptoms",
    "Contraceptive history",
  ],
  "Obstetric History": [
    "Gravida/Para status",
    "Antenatal complications",
    "Previous cesarean section",
    "Miscarriage history",
    "Fetal movement status",
    "Hypertension during pregnancy",
    "Gestational diabetes",
  ],
  "Pediatric History": [
    "Birth history",
    "NICU admission",
    "Vaccination status",
    "Developmental milestones",
    "Feeding history",
    "Recurrent infections",
    "Growth abnormalities",
    "School performance",
  ],
  "Psychiatric History": [
    "Anxiety",
    "Depression",
    "Mood swings",
    "Hallucinations",
    "Delusions",
    "Sleep disturbances (Psych)",
    "Suicidal thoughts",
    "Substance abuse",
    "Behavioral issues",
  ],
  "Dermatology History": [
    "Skin rash",
    "Itching (Skin)",
    "Scaling",
    "Ulcers",
    "Pigmentation",
    "Acne",
    "Hair fall",
    "Nail changes",
    "Allergy history (Skin)",
  ],
  "Endocrinology History": [
    "Diabetes mellitus",
    "Thyroid disorders",
    "Weight gain/loss",
    "Polyuria",
    "Polydipsia",
    "Heat intolerance",
    "Cold intolerance",
    "Hormonal imbalance",
  ],
  "Oncology History": [
    "Weight loss (Onco)",
    "Loss of appetite (Onco)",
    "Lump/swelling",
    "Bleeding history",
    "Fatigue (Onco)",
    "Previous chemotherapy",
    "Radiation history",
    "Family history of cancer",
  ],
  "Rheumatology History": [
    "Joint swelling",
    "Morning stiffness (Rheum)",
    "Autoimmune disorders",
    "Fatigue (Rheum)",
    "Muscle pain",
    "Skin manifestations",
  ],
  "Physiotherapy History": [
    "Functional limitation",
    "Pain assessment",
    "Muscle weakness (Physio)",
    "Balance issues",
    "Gait abnormalities",
    "Mobility restriction",
    "Previous physiotherapy sessions",
  ],
  "Dental History": [
    "Tooth pain",
    "Gum bleeding",
    "Sensitivity",
    "Bad breath",
    "Dental caries",
    "Tooth extraction history",
    "Orthodontic treatment",
  ],
  "Rehabilitation History": [
    "Functional limitation",
    "Pain assessment",
    "Muscle weakness (Physio)",
    "Balance issues",
    "Gait abnormalities",
    "Mobility restriction",
    "Previous physiotherapy sessions",
    "Rehabilitation history",
  ],
};
